apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ouroboros-agent.fullname" . }}-secrets
  labels:
    {{- include "ouroboros-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets | nindent 2 }}
