import { callLLMWithResilience, type LLMConfig } from "../../core/llm-resilience.ts";
import type { BaseMessage, AssistantMessage, Tool } from "../../types/index.ts";

export interface LLMCaller {
  call(messages: BaseMessage[], tools: Tool<unknown, unknown, unknown>[]): Promise<AssistantMessage>;
}

export function createRealLLMCaller(cfg: LLMConfig): LLMCaller {
  return {
    async call(messages, tools) {
      const result = await callLLMWithResilience(cfg, messages, tools);
      if (!result.success) {
        throw new Error(`LLM error: ${result.error.message}`);
      }
      return result.data;
    },
  };
}

export function createMockLLMCaller(): LLMCaller {
  return {
    async call(messages, tools) {
      const lastUser = messages.findLast((m) => m.role === "user");
      const text = (lastUser?.content as string) || "";

      // Detect if we already successfully wrote a skill in the previous turn
      const lastAssistant = messages.findLast((m) => m.role === "assistant");
      const lastToolResult = messages.findLast((m) => m.role === "tool_result");
      let alreadyWroteSkill = false;
      if (lastAssistant && Array.isArray(lastAssistant.content)) {
        const hadWriteSkill = lastAssistant.content.some(
          (b: unknown) =>
            typeof b === "object" &&
            b !== null &&
            (b as { type?: string; name?: string }).type === "tool_use" &&
            (b as { type?: string; name?: string }).name === "write_skill"
        );
        const hadSuccessResult =
          lastToolResult &&
          typeof lastToolResult.content === "string" &&
          lastToolResult.content.includes('"success": true');
        alreadyWroteSkill = hadWriteSkill && !!hadSuccessResult;
      }

      if (alreadyWroteSkill) {
        return {
          role: "assistant",
          content: "Skill saved successfully. The system has learned this pattern.",
        };
      }

      if (text.includes("learn") && tools.some((t) => t.name === "write_skill")) {
        // Embed the user's directive into the skill body for demo realism
        const directive = text.replace(/learn this:?\s*/i, "").trim();
        const skillBody = directive || "This skill was generated by the Ouroboros learning loop.";
        return {
          role: "assistant",
          content: [
            { type: "text", text: "I will save this pattern as a skill." },
            {
              type: "tool_use",
              id: "tu_1",
              name: "write_skill",
              input: {
                name: "example-pattern",
                markdown:
                  "---\n" +
                  "name: example-pattern\n" +
                  `description: ${skillBody.slice(0, 60)}\n` +
                  "version: 0.1.0\n" +
                  "---\n\n" +
                  skillBody,
              },
            },
          ],
        };
      }

      if (text.includes("hello") || text.includes("你好")) {
        return {
          role: "assistant",
          content: "Hello. I am Ouroboros. How may I assist your evolution today?",
        };
      }

      // Simulate skill-aware behavior for demo purposes
      const systemMsg = messages.find((m) => m.role === "system")?.content as string;
      if (text.includes("nihao") && systemMsg?.includes("Chinese")) {
        return {
          role: "assistant",
          content: "你好！我是 Ouroboros。今天想如何进化？",
        };
      }

      return {
        role: "assistant",
        content: `I received: "${text}". Available tools: ${tools.map((t) => t.name).join(", ")}`,
      };
    },
  };
}
