import { useState } from 'react'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { Sparkles, Download, Loader2, CheckCircle, XCircle, Wand2, Shield, AlertTriangle, AlertOctagon } from 'lucide-react'
import { apiFetch } from '../api.js'

async function installSkill(source) {
  const res = await apiFetch('/api/skills/install', {
    method: 'POST',
    body: JSON.stringify({ source: source.trim() }),
  })
  return res.json()
}

async function generateSkill(payload) {
  const res = await apiFetch('/api/skills/generate', {
    method: 'POST',
    body: JSON.stringify(payload),
  })
  return res.json()
}

function isAutoGenerated(skill) {
  return (skill.tags || []).some((t) => t === 'generated' || t === 'autonomous' || t === 'evolution')
}

function getSecurityIcon(skill) {
  let scan
  try {
    scan = skill.securityScan ? JSON.parse(skill.securityScan) : null
  } catch {
    scan = null
  }
  if (!scan) return null
  if (scan.verdict === 'safe') {
    return <Shield className="w-3.5 h-3.5 text-ok" title="Safe" />
  }
  if (scan.verdict === 'caution') {
    return <AlertTriangle className="w-3.5 h-3.5 text-warn" title={`Caution: ${scan.findings?.length || 0} finding(s)`} />
  }
  if (scan.verdict === 'dangerous') {
    return <AlertOctagon className="w-3.5 h-3.5 text-danger" title={`Dangerous: ${scan.findings?.length || 0} finding(s)`} />
  }
  return null
}

export function SkillManager({ skills }) {
  const [source, setSource] = useState('')
  const queryClient = useQueryClient()

  const installMutation = useMutation({
    mutationFn: installSkill,
    onSuccess: (data) => {
      if (data.success) {
        queryClient.invalidateQueries({ queryKey: ['skills'] })
      }
    },
  })

  const generateMutation = useMutation({
    mutationFn: generateSkill,
    onSuccess: (data) => {
      if (data.success) {
        queryClient.invalidateQueries({ queryKey: ['skills'] })
      }
    },
  })

  const handleInstall = () => {
    if (!source.trim() || installMutation.isPending) return
    installMutation.mutate(source)
    setSource('')
  }

  const handleGenerate = (skill) => {
    if (generateMutation.isPending) return
    generateMutation.mutate({
      skill_name: skill.name,
      description: skill.description,
      problem_statement: `Generate executable code for the skill "${skill.name}"`,
      force: true,
    })
  }

  return (
    <div className="space-y-6">
      {/* Install Card */}
      <div className="bg-card border border-border rounded-xl p-5">
        <h2 className="text-lg font-semibold text-text-strong mb-4 flex items-center gap-2">
          <Download className="w-5 h-5 text-accent" />
          安装 Skill
        </h2>
        <div className="flex gap-3">
          <input
            value={source}
            onChange={(e) => setSource(e.target.value)}
            placeholder="输入 Git URL 或本地路径"
            className="flex-1 bg-secondary border border-border rounded-lg px-4 py-2 text-sm outline-none focus:border-accent"
          />
          <button
            onClick={handleInstall}
            disabled={installMutation.isPending || !source.trim()}
            className="px-4 py-2 bg-accent hover:bg-accent-hover disabled:bg-secondary rounded-lg text-white text-sm flex items-center gap-2 transition"
          >
            {installMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
            安装
          </button>
        </div>
        {installMutation.isSuccess && (
          <div className={`mt-3 text-sm flex items-start gap-2 ${installMutation.data.success ? 'text-ok' : 'text-danger'}`}>
            {installMutation.data.success ? <CheckCircle className="w-4 h-4 mt-0.5" /> : <XCircle className="w-4 h-4 mt-0.5" />}
            <div>
              {installMutation.data.success
                ? `成功安装: ${(installMutation.data.data?.installed || []).map((i) => i.name).join(', ') || '无新技能'}`
                : installMutation.data.error?.message || '安装失败'}
            </div>
          </div>
        )}
      </div>

      {/* Generation feedback */}
      {generateMutation.isSuccess && (
        <div className={`text-sm flex items-start gap-2 ${generateMutation.data.success ? 'text-ok' : 'text-danger'}`}>
          {generateMutation.data.success ? <CheckCircle className="w-4 h-4 mt-0.5" /> : <XCircle className="w-4 h-4 mt-0.5" />}
          <div>
            {generateMutation.data.success
              ? `代码生成成功: ${generateMutation.data.data.toolsLoaded?.join(', ') || '无工具导出'}`
              : generateMutation.data.error?.message || '生成失败'}
          </div>
        </div>
      )}

      {/* Skills Grid */}
      <div>
        <h2 className="text-lg font-semibold text-text-strong mb-4 flex items-center gap-2">
          <Sparkles className="w-5 h-5 text-accent" />
          已安装 Skills
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {skills.map((s) => (
            <div key={s.name} className="bg-card border border-border rounded-xl p-4 hover:border-accent/50 transition">
              <div className="flex items-start justify-between mb-2">
                <div className="flex items-center gap-2">
                  <h3 className="font-semibold text-text-strong">{s.name}</h3>
                  {isAutoGenerated(s) && (
                    <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-accent/20 text-accent border border-accent/30">
                      自动生成
                    </span>
                  )}
                  {getSecurityIcon(s)}
                </div>
                <span className="text-xs px-2 py-0.5 rounded-full bg-secondary text-muted">{s.version}</span>
              </div>
              <p className="text-sm text-muted mb-3 line-clamp-2">{s.description}</p>
              <div className="flex flex-wrap gap-1 mb-3">
                {(s.tags || []).map((tag) => (
                  <span key={tag} className="text-[10px] px-1.5 py-0.5 rounded bg-secondary/70 text-muted">
                    {tag}
                  </span>
                ))}
              </div>
              {!s.hasCode && (
                <button
                  onClick={() => handleGenerate(s)}
                  disabled={generateMutation.isPending}
                  className="text-xs flex items-center gap-1 px-2 py-1 rounded bg-secondary hover:bg-secondary/80 text-muted transition"
                >
                  {generateMutation.isPending && generateMutation.variables?.skill_name === s.name ? (
                    <Loader2 className="w-3 h-3 animate-spin" />
                  ) : (
                    <Wand2 className="w-3 h-3" />
                  )}
                  生成代码
                </button>
              )}
            </div>
          ))}
          {skills.length === 0 && (
            <div className="col-span-full text-center text-sm text-muted py-12 bg-card border border-border rounded-xl">
              暂无已安装技能
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
